# Generated by Django 4.2.2 on 2023-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('phoneno', models.CharField(max_length=15)),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('accounttype', models.CharField(choices=[('S', 'Savings'), ('C', 'Current'), ('F', 'Fixed')], max_length=20)),
                ('materials', models.CharField(choices=[('D', 'Debit card'), ('C', 'Credit card'), ('P', 'Cheque book')], max_length=50)),
            ],
        ),
    ]
